import bsky from '@atproto/api'
import * as dotenv from 'dotenv'
dotenv.config();

import { getGradientImage } from './generateGradientImage.js';

import fs from "fs";
const { BskyAgent, RichText, } = bsky;

start();


async function start(){

    const agent = new BskyAgent({
        service: process.env.BLUESKY_IDENTIFIER
    })


    await agent.login({
        identifier: process.env.BLUESKY_USERNAME,
        password: process.env.BLUESKY_PASSWORD
    });

   const {path: imagePath, startColor, endColor} = await getGradientImage();
   const file = fs.readFileSync(imagePath)
   
    const response = await agent.uploadBlob(file, {
        encoding: "image/jpeg",
    })


if (!response.success) {
    const msg = `Unable to upload image`// ${imageUrl}`;
    console.error(msg, response);
    throw new Error(msg);
}

const {
    data: { blob: image },
} = response;


    const rt = new RichText({ text: `computer-generated gradient from ${startColor} to ${endColor}` });
    await rt.detectFacets(agent);


return agent.post({
    text: rt.text,
    facets: rt.facets,
    embed: {
        $type: "app.bsky.embed.images",
        images: [
            {
                image: image,
                alt: "a gradient generated by p5 code"
            },
        ],
    },
});

}

