import bsky from '@atproto/api'
import * as dotenv from 'dotenv'
import { getGradientImage } from './generateGradientImage.js';

import fs from "fs";
const {BskyAgent} = bsky;

const agent = new BskyAgent({
    service: 'https://bsky.social'
})

dotenv.config();

start();


async function start(){
    await agent.login({
        identifier: process.env.BLUESKY_USERNAME,
        password: process.env.BLUESKY_PASSWORD
    });

    const imageUrl = getGradientImage()//'./myCanvas.jpg'
   
    const response = await agent.uploadBlob(imageUrl, {
        encoding: "image/jpeg",
    })

    
if (!response.success) {
    const msg = `Unable to upload image`// ${imageUrl}`;
    console.error(msg, response);
    throw new Error(msg);
}

const {
    data: { blob: image },
} = response;


return agent.post({
    text: 'testing image upload',
    embed: {
        $type: "app.bsky.embed.images",
        images: [
            {
                image: image,
                alt: "a gradient generated by p5 code"
            },
        ],
    },
});

}
